// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CashflowFilterController from "./cashflow_filter_controller.js"
application.register("cashflow-filter", CashflowFilterController)

import ChoiceSelectController from "./choice_select_controller.js"
application.register("choice-select", ChoiceSelectController)

import ColorPickerController from "./color_picker_controller.js"
application.register("color-picker", ColorPickerController)

import ColorizerController from "./colorizer_controller.js"
application.register("colorizer", ColorizerController)

import DashboardAmountLoaderController from "./dashboard_amount_loader_controller.js"
application.register("dashboard-amount-loader", DashboardAmountLoaderController)

import ExpenseCategoryFilterController from "./expense_category_filter_controller.js"
application.register("expense-category-filter", ExpenseCategoryFilterController)

import IconPickerController from "./icon_picker_controller.js"
application.register("icon-picker", IconPickerController)
